### ISSUE TITLE
Typos & Bad Links

### ISSUE THREAD

**Issue by skylee03** [scmlab/guabao-homepage#2]
# Typos in "Tutorial"

1. "Gaubao" should be "Guabao".
![image](https://user-images.githubusercontent.com/24489025/159831975-f10c068c-803a-4299-b2d0-f316196b83ee.png)

2. "non-egative" should be "non-negative".
![image](https://user-images.githubusercontent.com/24489025/159832068-f04be522-a16d-40f8-8f68-337e081dee47.png)

3. We should press `\` to input Unicode characters.
![image](https://user-images.githubusercontent.com/24489025/159832575-bc06718d-9cee-43c2-9e67-64aa6f9f4944.png)

# Bad Links in "GCL Overview"

1. The link in leads to "https://scmlab.github.io/guabao/pages/pages/4-references.html", but it should lead to "https://scmlab.github.io/guabao/pages/4-references.html".
![image](https://user-images.githubusercontent.com/24489025/159833005-9d072f9a-da86-48f3-a27a-eee9fc2f3336.png)

**Comment by scmu** [comment]
Thank you for your interest in this project and for spotting these typos! Sorry that it took so long to respond --- we were preparing a paper on Guabao and were too occupied. 

I believe that these issues are fixed now.

If you have used Guabao and found bugs/errors, feel free reporting them here:
https://github.com/scmlab/gcl

Thank you again!
